# generated by datamodel-codegen:
#   filename:  grid.json
#   timestamp: 2025-05-06T04:46:17+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class Side(Enum):
    neutral = 'neutral'
    front = 'front'
    back = 'back'


class GridCellKey(Enum):
    Flip = 'Flip'
    Empty = 'Empty'
    Normal = 'Normal'
    Start = 'Start'
    Goal = 'Goal'
    DummyGoal = 'DummyGoal'
    Crow = 'Crow'
    Wolf = 'Wolf'
    Warp = 'Warp'
    ArrowUpDown = 'ArrowUpDown'
    ArrowRightLeft = 'ArrowRightLeft'
    Rest = 'Rest'


class GridCell(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    side: Side
    type: GridCellKey


class Grid(RootModel[List[List[GridCell]]]):
    root: List[List[GridCell]]


class Model(RootModel[Grid]):
    root: Grid
