# generated by datamodel-codegen:
#   filename:  grid.json
#   timestamp: 2025-04-29T14:27:47+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra


class Side(Enum):
    neutral = 'neutral'
    front = 'front'
    back = 'back'


class GridCellKey(Enum):
    Flip = 'Flip'
    Empty = 'Empty'
    Normal = 'Normal'
    Start = 'Start'
    Goal = 'Goal'
    DummyGoal = 'DummyGoal'
    Crow = 'Crow'
    Wolf = 'Wolf'
    Warp = 'Warp'
    ArrowUpDown = 'ArrowUpDown'
    ArrowRightLeft = 'ArrowRightLeft'
    Rest = 'Rest'


class GridCell(BaseModel):
    class Config:
        extra = Extra.forbid

    side: Side
    type: GridCellKey


class Grid(BaseModel):
    __root__: List[List[GridCell]]


class Model(BaseModel):
    __root__: Grid
