# generated by datamodel-codegen:
#   filename:  panel-placement.json
#   timestamp: 2025-06-09T10:36:05+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PanelCellTypeKey(Enum):
    White = 'White'
    Black = 'Black'


class Vector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class Panel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cells: List[List[PanelCellTypeKey]]
    id: str


class PanelPlacement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    highlight: Vector
    panel: Panel
    point: Vector


class Model(RootModel[PanelPlacement]):
    root: PanelPlacement
