# generated by datamodel-codegen:
#   filename:  panel-placement.json
#   timestamp: 2025-05-07T05:46:09+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, RootModel

# Vector, Panelまで自動生成されるので、Panelモデル内に統合すべきかもしれない
from models.path import Vector
from models.panel import Panel

# class PanelCellTypeKey(Enum):
#     White = 'White'
#     Black = 'Black'


# class Vector(BaseModel):
#     model_config = ConfigDict(
#         extra='forbid',
#     )
#     x: int     # floatと自動生成されたので、intに変更
#     y: int  


# class Panel(BaseModel):
#     model_config = ConfigDict(
#         extra='forbid',
#     )
#     cells: List[List[PanelCellTypeKey]]
#     id: str


class PanelPlacement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    highlight: Vector
    panel: Panel
    point: Vector


class Model(RootModel[PanelPlacement]):
    root: PanelPlacement
