# generated by datamodel-codegen:
#   filename:  panel.json
#   timestamp: 2025-04-29T14:28:00+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra


class PanelCellTypeKey(Enum):
    White = 'White'
    Black = 'Black'


class Panel(BaseModel):
    class Config:
        extra = Extra.forbid

    cells: List[List[PanelCellTypeKey]]
    id: str


class Model(BaseModel):
    __root__: Panel
