# generated by datamodel-codegen:
#   filename:  panel.json
#   timestamp: 2025-06-09T10:35:56+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class PanelCellTypeKey(Enum):
    White = 'White'
    Black = 'Black'


class Panel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cells: List[List[PanelCellTypeKey]]
    id: str


class Model(RootModel[Panel]):
    root: Panel
