# generated by datamodel-codegen:
#   filename:  path.json
#   timestamp: 2025-05-05T11:25:59+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra


class Result(Enum):
    NoPath = 'NoPath'
    HasClearPath = 'HasClearPath'
    HasFailPath = 'HasFailPath'


class Vector(BaseModel):
    class Config:
        extra = Extra.forbid

    x: float
    y: float


class Path(BaseModel):
    __root__: List[Vector]


class PathResult(BaseModel):
    class Config:
        extra = Extra.forbid

    path: Path
    result: Result


class Model(BaseModel):
    __root__: PathResult
