# generated by datamodel-codegen:
#   filename:  path.json
#   timestamp: 2025-05-06T04:48:27+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, ConfigDict, RootModel


class Result(Enum):
    NoStart = 'NoStart'
    NoGoal = 'NoGoal'
    NoPath = 'NoPath'
    HasClearPath = 'HasClearPath'
    HasFailPath = 'HasFailPath'


class Vector(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float


class Path(RootModel[List[Vector]]):
    root: List[Vector]


class PathResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Path
    result: Result


class Model(RootModel[PathResult]):
    root: PathResult
